---
platform: ppc64le

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.31:5000/bosh
    insecure_registries: ["140.211.168.31:5000"]

inputs:
- name: bosh-fuzz-tests
- name: bosh-src

run:
  path: bosh-fuzz-tests/ci/tasks/test.sh

params:
  RUBY_VERSION: 2.3
