---
platform: ppc64le

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.31:5000/bosh
    insecure_registries: ["140.211.168.31:5000"]

inputs:
- name: bosh-load-tests-workspace
- name: bosh-src

run:
  path: bosh-load-tests-workspace/ci/tasks/test.sh

params:
  DB: postgresql
  RUBY_VERSION: 2.3
  LEGACY: false
