---
platform: ppc64le

image_resource:
  type: docker-image
  source:
    repository: 140.211.168.31:5000/bosh
    insecure_registries: ["140.211.168.31:5000"]

inputs:
  - name: bosh-src
  - name: ppc64le-tests

run:
  path: ppc64le-tests/ci/tasks/test-unit.sh

params:
  RUBY_VERSION: replace-me
  DB:           replace-me