---
platform: linux

image: /var/vcap/store/bosh_rootfs

inputs:
- name: bosh-src
- name: ppc64le-tests

run:
  path: ppc64le-tests/ci/tasks/test-integration.sh

params:
  RUBY_VERSION: replace-me
  DB:           replace-me
  LOG_LEVEL:    INFO
  NUM_GROUPS:   16
