---
platform: linux

image: docker://172.29.161.184:5000/bosh

inputs:
  - name: bosh-src
  - name: ppc64le-tests

run:
  path: ppc64le-tests/ci/tasks/test-unit.sh

params:
  RUBY_VERSION: replace-me
