---
groups:
  - name: bosh
    jobs:
      - start-job
      - unit-2.3
      - integration-2.3-mysql
      - integration-2.3-postgres

  - name: 2.3
    jobs:
      - start-job
      - unit-2.3
      - integration-2.3-mysql
      - integration-2.3-postgres
  - name: mysql
    jobs:
      - start-job
      - unit-2.3
      - integration-2.3-mysql

  - name: postgres
    jobs:
      - start-job
      - unit-2.3
      - integration-2.3-postgres

jobs:
  - name: start-job
    public: true
    serial: true
    plan:
      - { get: interval-trigger, trigger: true }
      - { get: bosh-src }
      - { get: ppc64le-tests }

  - name: unit-2.3
    public: true
    serial: true
    plan:
    - aggregate:
      - { get: bosh-src, trigger: true, passed: [start-job] }
      - { get: ppc64le-tests, trigger: false, passed: [start-job] }
    - task: test
      privileged: true
      file: ppc64le-tests/ci/tasks/test-unit.yml
      params:
        RUBY_VERSION: 2.3.1

  - name: integration-2.3-mysql
    public: true
    serial: true
    plan:
    - aggregate:
      - { get: bosh-src, trigger: true, passed: [start-job] }
      - { get: ppc64le-tests, trigger: false, passed: [start-job] }

    - task: test
      privileged: true
      file: ppc64le-tests/ci/tasks/test-integration.yml
      params:
        DB:           mysql
        RUBY_VERSION: 2.3.1
        NUM_GROUPS: 2

  - name: integration-2.3-postgres
    public: true
    serial: true
    plan:
    - aggregate:
      - { get: bosh-src, trigger: true, passed: [start-job] }
      - { get: ppc64le-tests, trigger: false, passed: [start-job] }
    - task: test
      privileged: true
      file: ppc64le-tests/ci/tasks/test-integration.yml
      params:
        DB:           postgresql
        RUBY_VERSION: 2.3.1
        NUM_GROUPS: 2


resources:
  - name: interval-trigger
    type: time
    source:
      interval: 90m # average build time for the integration tests

  - name: ppc64le-tests
    type: git
    source:
      uri: https://github.com/barthy1/ppc64le_tests.git
      branch: master

  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: develop
